import { componentRegistry, lazy } from "./registryCore";

export function registerMapComponents(): void {
  componentRegistry.register({
    type: "map-tile",
    name: "瓦片地图",
    icon: "map",
    description: "2D 瓦片地图，支持 OSM/天地图/高德等瓦片服务",
    category: "map",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    layerType: "spatial",
    defaultSize: { width: 800, height: 600 },
    defaultConfig: {
      tileUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      crs: "EPSG:3857",
      center: [116.397, 39.908],
      zoom: 10,
      minZoom: 0,
      maxZoom: 18,
      pitch: 0,
      bearing: 0,
      showControls: true,
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: true,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/TileMapRenderer").then(m => ({ default: m.TileMapRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "regionClick", name: "区域点击" },
      { id: "zoomChange", name: "缩放变化" },
      { id: "moveEnd", name: "移动结束" },
    ],
    actions: [
      { id: "flyTo", name: "飞行到" },
      { id: "fitBounds", name: "适配范围" },
      { id: "addLayer", name: "添加图层" },
      { id: "removeLayer", name: "移除图层" },
    ],
    configSchema: [
      { key: "mapLibraryId", label: "已发布瓦片图库", type: "mapLibrary", mapType: "tile", group: "数据源" },
      { key: "tileUrl", label: "瓦片地址", type: "text", group: "数据源" },
      { key: "crs", label: "坐标系", type: "select", options: [
        { label: "EPSG:3857 (Web墨卡托)", value: "EPSG:3857" },
        { label: "EPSG:4326 (WGS84)", value: "EPSG:4326" },
        { label: "EPSG:4490 (CGCS2000)", value: "EPSG:4490" },
      ], group: "数据源" },
      { key: "center", label: "中心点", type: "text", group: "视口" },
      { key: "zoom", label: "缩放级别", type: "number", min: 0, group: "视口" },
      { key: "minZoom", label: "最小缩放", type: "number", min: 0, group: "视口" },
      { key: "maxZoom", label: "最大缩放", type: "number", min: 0, group: "视口" },
      { key: "pitch", label: "倾斜角", type: "number", min: 0, group: "视口" },
      { key: "bearing", label: "旋转角", type: "number", min: 0, group: "视口" },
      { key: "showControls", label: "显示控件", type: "toggle", group: "交互" },
    ],
  });

  componentRegistry.register({
    type: "map-cad",
    name: "CAD图纸",
    icon: "architecture",
    description: "CAD 图纸查看组件，支持 DXF/DWG 格式",
    category: "map",
    version: "3.0.0",
    builtIn: true,
    enabled: true,
    layerType: "spatial",
    defaultSize: { width: 800, height: 600 },
    defaultConfig: {
      mapLibraryId: "",
      backgroundColor: "#1a1a2e",
      lineColor: "#4fc3f7",
      backgroundOpacity: 1,
      contentOpacity: 1,
      fitMode: "contain",
      showBorder: false,
      borderColor: "#666666",
      borderWidth: 1,
      cameraState: null,
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: true,
      embeddable: true,
    },
    renderer: lazy(() => import("./renderers/CADMapRenderer").then(m => ({ default: m.CADMapRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "entityClick", name: "实体点击" },
      { id: "documentLoaded", name: "文档加载完成" },
    ],
    actions: [
      { id: "zoomToFit", name: "适配视图" },
      { id: "highlight", name: "高亮实体" },
    ],
    configSchema: [
      { key: "mapLibraryId", label: "已发布地图", type: "mapLibrary", mapType: "cad", group: "数据源" },
      { key: "fitMode", label: "适配模式", type: "select", options: [
        { label: "填充", value: "contain" },
        { label: "铺满", value: "cover" },
        { label: "拉伸", value: "stretch" },
        { label: "自定义", value: "custom" },
      ], group: "布局" },
      { key: "backgroundColor", label: "背景色", type: "color", group: "样式" },
      { key: "backgroundOpacity", label: "背景透明度", type: "slider", min: 0, step: 0.05, group: "样式", max: 1 },
      { key: "lineColor", label: "线条颜色", type: "color", group: "样式" },
      { key: "contentOpacity", label: "图纸透明度", type: "slider", min: 0, step: 0.05, group: "样式", max: 1 },
      { key: "showBorder", label: "显示边框", type: "toggle", group: "边框" },
      { key: "borderColor", label: "边框颜色", type: "color", group: "边框", hidden: (c) => !c.showBorder },
      { key: "borderWidth", label: "边框宽度", type: "number", min: 0, step: 1, group: "边框", hidden: (c) => !c.showBorder },
    ],
  });

  // ─── CAD 装饰增强层（极致纯净版：仅 4 角圆点 + 4 角光晕，0 横竖、0 线段、0 矩形） ───
  componentRegistry.register({
    type: "cad-enhancer",
    name: "CAD 装饰增强",
    icon: "auto_awesome",
    description: "在 CAD 4 角添加圆形点 + 圆形径向光晕（仅 <circle> 元素，零 line/path/rect；容器完全透明；pointer-events:none）",
    category: "decoration",
    version: "1.4.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 2160, height: 1200 },
    defaultConfig: { accent: "#4fc3f7", showCorners: true, showHalo: true },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/CADEnhancerRenderer").then(m => ({ default: m.CADEnhancerRenderer }))),
    events: [],
    actions: [],
    dataSchema: { sourceType: "static", staticData: {} },
    configSchema: [
      { key: "accent", label: "主色调", type: "color", group: "配色", defaultValue: "#4fc3f7" },
      { key: "accent2", label: "副色", type: "color", group: "配色", defaultValue: "#aedfff" },

      { key: "showCorners", label: "4 角点装饰", type: "toggle", group: "四角", defaultValue: true },
      { key: "cornerSize", label: "角点装饰半径", type: "slider", min: 6, max: 30, step: 1, group: "四角", defaultValue: 14 },
      { key: "dotSize", label: "中心高亮大小", type: "slider", min: 1, max: 6, step: 0.5, group: "四角", defaultValue: 2.5 },
      { key: "showHalo", label: "4 角光晕", type: "toggle", group: "四角", defaultValue: true },
    ],
  });

  componentRegistry.register({
    type: "map-blueprint",
    name: "图片蓝图",
    icon: "wallpaper",
    description: "图片蓝图/平面图，支持图片配准叠加到地图",
    category: "map",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    layerType: "spatial",
    defaultSize: { width: 800, height: 600 },
    defaultConfig: {
      imageUrl: "",
      bounds: { min: { x: 116.2, y: 39.7 }, max: { x: 116.5, y: 40.0 } },
      opacity: 1,
      showBaseMap: true,
      baseMapUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: true,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/BlueprintMapRenderer").then(m => ({ default: m.BlueprintMapRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "regionClick", name: "区域点击" },
    ],
    actions: [
      { id: "flyTo", name: "飞行到" },
      { id: "updateImage", name: "更新图片" },
    ],
    configSchema: [
      { key: "mapLibraryId", label: "已发布蓝图图库", type: "mapLibrary", mapType: "blueprint", group: "数据源" },
      { key: "imageUrl", label: "图片地址", type: "text", group: "数据源" },
      { key: "bounds", label: "坐标范围", type: "json", group: "配准" },
      { key: "opacity", label: "透明度", type: "number", min: 0, step: 0.1, group: "样式" },
      { key: "showBaseMap", label: "显示底图", type: "toggle", group: "底图" },
      { key: "baseMapUrl", label: "底图地址", type: "text", group: "底图" },
    ],
  });

  componentRegistry.register({
    type: "map-globe",
    name: "三维地球",
    icon: "public",
    description: "三维地球组件，支持 3D Tiles、地形、三维模型",
    category: "map",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    layerType: "spatial",
    defaultSize: { width: 800, height: 600 },
    defaultConfig: {
      ionAccessToken: "",
      terrainEnabled: true,
      imageryProvider: "osm",
      center: [116.397, 39.908],
      zoom: 10,
      pitch: -30,
      bearing: 0,
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: true,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/GlobeMapRenderer").then(m => ({ default: m.GlobeMapRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "entityClick", name: "实体点击" },
      { id: "cameraChanged", name: "相机变化" },
    ],
    actions: [
      { id: "flyTo", name: "飞行到" },
      { id: "add3DTiles", name: "添加3DTiles", disabled: true, disabledReason: "3DTiles加载需要集成CesiumJS，当前使用Three.js基础地球" },
      { id: "addEntity", name: "添加实体", disabled: true, disabledReason: "实体添加需要集成CesiumJS Entity API，当前使用Three.js基础地球" },
    ],
    configSchema: [
      { key: "ionAccessToken", label: "Ion Token", type: "text", group: "数据源" },
      { key: "terrainEnabled", label: "启用地形", type: "toggle", group: "数据源" },
      { key: "imageryProvider", label: "影像底图", type: "select", options: [
        { label: "OpenStreetMap", value: "osm" },
        { label: "天地图", value: "tianditu" },
        { label: "无底图", value: "none" },
      ], group: "数据源" },
      { key: "center", label: "中心点", type: "text", group: "视口" },
      { key: "zoom", label: "缩放级别", type: "number", min: 0, group: "视口" },
      { key: "pitch", label: "倾斜角", type: "number", min: 0, group: "视口" },
    ],
  });

  componentRegistry.register({
    type: "map-heatmap",
    name: "热力地图",
    icon: "whatshot",
    description: "热力图/数据可视化地图，支持热力、轨迹、聚合等",
    category: "map",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    layerType: "spatial",
    defaultSize: { width: 800, height: 600 },
    defaultConfig: {
      baseMapUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      heatmapRadius: 30,
      heatmapIntensity: 1,
      heatmapOpacity: 0.8,
      data: [],
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: true,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/HeatmapMapRenderer").then(m => ({ default: m.HeatmapMapRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "pointClick", name: "数据点点击" },
    ],
    actions: [
      { id: "updateData", name: "更新数据" },
      { id: "flyTo", name: "飞行到" },
      { id: "setStyle", name: "设置样式" },
    ],
    dataSchema: {
      sourceType: "static",
      staticData: [],
    },
    configSchema: [
      { key: "baseMapUrl", label: "底图地址", type: "text", group: "底图" },
      { key: "heatmapRadius", label: "热力半径", type: "number", min: 0, group: "样式" },
      { key: "heatmapIntensity", label: "热力强度", type: "number", min: 0.1, step: 0.1, group: "样式" },
      { key: "heatmapOpacity", label: "透明度", type: "number", min: 0, step: 0.1, group: "样式" },
    ],
  });
}
