import { componentRegistry, lazy } from "./registryCore";

export function registerBasicComponents(): void {
  componentRegistry.register({
    type: "text",
    name: "文本",
    icon: "text_fields",
    description: "文本组件，支持丰富排版、数据绑定、渐变文字、动画效果",
    category: "basic",
    version: "2.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 240, height: 80 },
    defaultConfig: {
      content: "文本内容",
      dataTemplate: "",
      autoFit: true,
      fontFamily: "inherit",
      fontSize: 16,
      fontWeight: "normal",
      fontStyle: "normal",
      color: "#ffffff",
      textAlign: "center",
      verticalAlign: "middle",
      lineHeight: 1.5,
      letterSpacing: 0,
      gradientEnabled: false,
      gradientFrom: "#2196F3",
      gradientTo: "#FF9800",
      gradientDirection: "to-right",
      textDecoration: "none",
      textShadowEnabled: false,
      textShadowColor: "rgba(0,0,0,0.5)",
      textShadowBlur: 4,
      textShadowOffsetX: 1,
      textShadowOffsetY: 1,
      backgroundEnabled: false,
      backgroundColor: "#1a1a2e",
      backgroundOpacity: 80,
      borderEnabled: false,
      borderColor: "#ffffff",
      borderWidth: 1,
      borderRadius: 4,
      padding: 8,
      cursor: "default",
      hoverEffect: "none",
      animation: "none",
      animationDuration: 500,
      loopAnimation: "none",
      loopAnimationDuration: 2000,
      overflow: "hidden",
      marqueeDirection: "left",
      marqueeSpeed: 5000,
    },
    capabilities: {
      resizable: true,
      rotatable: true,
      draggable: true,
      connectable: true,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/TextRenderer").then(m => ({ default: m.TextRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "dblclick", name: "双击" },
    ],
    actions: [
      { id: "setContent", name: "更新内容" },
      { id: "setStyle", name: "更新样式" },
      { id: "highlight", name: "高亮" },
    ],
    dataSchema: {
      sourceType: "static",
      staticData: {},
    },
    configSchema: [
      { key: "content", label: "文本内容", type: "textarea", group: "内容" },
      { key: "autoFit", label: "自适应大小", type: "toggle", group: "内容" },
      { key: "fontFamily", label: "字体", type: "select", options: [
        { label: "默认", value: "inherit" },
        { label: "苹方", value: '"PingFang SC", sans-serif' },
        { label: "微软雅黑", value: '"Microsoft YaHei", sans-serif' },
        { label: "思源黑体", value: '"Source Han Sans CN", sans-serif' },
        { label: "宋体", value: "SimSun, serif" },
        { label: "黑体", value: "SimHei, sans-serif" },
        { label: "DIN (工业)", value: '"DIN Alternate", "Impact", sans-serif' },
        { label: "等宽字体", value: '"Courier New", monospace' },
      ], group: "排版" },
      { key: "fontSize", label: "字号", type: "number", min: 0, group: "排版" },
      { key: "fontWeight", label: "字重", type: "select", options: [
        { label: "正常", value: "normal" },
        { label: "粗体", value: "bold" },
        { label: "细体", value: "lighter" },
        { label: "100", value: "100" },
        { label: "200", value: "200" },
        { label: "300", value: "300" },
        { label: "400", value: "400" },
        { label: "500", value: "500" },
        { label: "600", value: "600" },
        { label: "700", value: "700" },
        { label: "800", value: "800" },
        { label: "900", value: "900" },
      ], group: "排版" },
      { key: "fontStyle", label: "字体样式", type: "select", options: [
        { label: "正常", value: "normal" },
        { label: "斜体", value: "italic" },
      ], group: "排版" },
      { key: "lineHeight", label: "行高", type: "number", min: 0, step: 0.1, group: "排版" },
      { key: "letterSpacing", label: "字间距", type: "number", min: 0, step: 0.5, group: "排版" },
      { key: "textAlign", label: "水平对齐", type: "select", options: [
        { label: "左对齐", value: "left" },
        { label: "居中", value: "center" },
        { label: "右对齐", value: "right" },
        { label: "两端对齐", value: "justify" },
      ], group: "排版" },
      { key: "verticalAlign", label: "垂直对齐", type: "select", options: [
        { label: "顶部", value: "top" },
        { label: "居中", value: "middle" },
        { label: "底部", value: "bottom" },
      ], group: "排版" },
      { key: "color", label: "文字颜色", type: "color", group: "颜色" },
      { key: "gradientEnabled", label: "渐变文字", type: "toggle", group: "颜色" },
      { key: "gradientFrom", label: "渐变起始色", type: "color", group: "颜色", hidden: (c) => !c.gradientEnabled },
      { key: "gradientTo", label: "渐变终止色", type: "color", group: "颜色", hidden: (c) => !c.gradientEnabled },
      { key: "gradientDirection", label: "渐变方向", type: "select", options: [
        { label: "从左到右", value: "to-right" },
        { label: "从右到左", value: "to-left" },
        { label: "从上到下", value: "to-bottom" },
        { label: "从下到上", value: "to-top" },
        { label: "左上到右下", value: "to-right-bottom" },
        { label: "右上到左下", value: "to-left-bottom" },
      ], group: "颜色", hidden: (c) => !c.gradientEnabled },
      { key: "textDecoration", label: "文字装饰", type: "select", options: [
        { label: "无", value: "none" },
        { label: "下划线", value: "underline" },
        { label: "删除线", value: "line-through" },
        { label: "上划线", value: "overline" },
      ], group: "装饰" },
      { key: "textShadowEnabled", label: "文字阴影", type: "toggle", group: "装饰" },
      { key: "textShadowColor", label: "阴影颜色", type: "color", group: "装饰", hidden: (c) => !c.textShadowEnabled },
      { key: "textShadowBlur", label: "阴影模糊", type: "number", min: 0, group: "装饰", hidden: (c) => !c.textShadowEnabled },
      { key: "textShadowOffsetX", label: "阴影X偏移", type: "number", min: 0, group: "装饰", hidden: (c) => !c.textShadowEnabled },
      { key: "textShadowOffsetY", label: "阴影Y偏移", type: "number", min: 0, group: "装饰", hidden: (c) => !c.textShadowEnabled },
      { key: "backgroundEnabled", label: "背景", type: "toggle", group: "背景" },
      { key: "backgroundColor", label: "背景色", type: "color", group: "背景", hidden: (c) => !c.backgroundEnabled },
      { key: "backgroundOpacity", label: "背景透明度", type: "slider", min: 0, step: 5, group: "背景", max: 1, hidden: (c) => !c.backgroundEnabled },
      { key: "borderEnabled", label: "边框", type: "toggle", group: "背景" },
      { key: "borderColor", label: "边框颜色", type: "color", group: "背景", hidden: (c) => !c.borderEnabled },
      { key: "borderWidth", label: "边框宽度", type: "number", min: 0, group: "背景", hidden: (c) => !c.borderEnabled },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "背景" },
      { key: "padding", label: "内边距", type: "number", min: 0, group: "背景" },
      { key: "cursor", label: "鼠标样式", type: "select", options: [
        { label: "默认", value: "default" },
        { label: "手型", value: "pointer" },
      ], group: "交互" },
      { key: "hoverEffect", label: "悬停效果", type: "select", options: [
        { label: "无", value: "none" },
        { label: "缩放", value: "scale" },
        { label: "发光", value: "glow" },
        { label: "高亮", value: "highlight" },
      ], group: "交互" },
      { key: "animation", label: "入场动画", type: "select", options: [
        { label: "无", value: "none" },
        { label: "淡入", value: "fadeIn" },
        { label: "上滑入", value: "slideUp" },
        { label: "下滑入", value: "slideDown" },
        { label: "左滑入", value: "slideLeft" },
        { label: "右滑入", value: "slideRight" },
        { label: "打字机", value: "typewriter" },
        { label: "逐字淡入", value: "charFadeIn" },
        { label: "逐行滑入", value: "lineSlideUp" },
        { label: "弹入", value: "bounceIn" },
        { label: "缩放进入", value: "zoomIn" },
        { label: "模糊进入", value: "blurIn" },
        { label: "翻转进入", value: "flipIn" },
      ], group: "动画" },
      { key: "animationDuration", label: "入场动画时长(ms)", type: "number", min: 0, step: 100, group: "动画", hidden: (c) => c.animation === "none" },
      { key: "loopAnimation", label: "循环动画", type: "select", options: [
        { label: "无", value: "none" },
        { label: "呼吸灯", value: "breathing" },
        { label: "闪烁", value: "blink" },
        { label: "脉冲", value: "pulse" },
        { label: "流动渐变", value: "flowingGradient" },
        { label: "光效扫过", value: "shineSweep" },
        { label: "跑马灯", value: "marquee" },
        { label: "淡入淡出轮播", value: "fadeCarousel" },
      ], group: "动画" },
      { key: "loopAnimationDuration", label: "循环动画时长(ms)", type: "number", min: 0, step: 100, group: "动画", hidden: (c) => c.loopAnimation === "none" },
      { key: "overflow", label: "溢出处理", type: "select", options: [
        { label: "隐藏", value: "hidden" },
        { label: "省略号", value: "ellipsis" },
        { label: "滚动", value: "scroll" },
        { label: "自动", value: "auto" },
      ], group: "动画" },
      { key: "marqueeDirection", label: "跑马灯方向", type: "select", options: [
        { label: "向左", value: "left" },
        { label: "向右", value: "right" },
        { label: "向上", value: "up" },
        { label: "向下", value: "down" },
      ], group: "动画", hidden: (c) => c.loopAnimation !== "marquee" },
      { key: "marqueeSpeed", label: "跑马灯速度(ms)", type: "number", min: 0, step: 500, group: "动画", hidden: (c) => c.loopAnimation !== "marquee" },
    ],
  });

  componentRegistry.register({
    type: "image",
    name: "图片",
    icon: "image",
    description: "图片组件",
    category: "basic",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 200 },
    defaultConfig: {
      source: "",
      fit: "cover",
      borderRadius: 0,
    },
    capabilities: {
      resizable: true,
      rotatable: true,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/ImageRenderer").then(m => ({ default: m.ImageRenderer }))),
    configSchema: [
      { key: "source", label: "图片", type: "file", group: "内容" },
      { key: "fit", label: "填充模式", type: "select", options: [
        { label: "覆盖", value: "cover" },
        { label: "包含", value: "contain" },
        { label: "拉伸", value: "fill" },
      ], group: "内容" },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "样式" },
    ],
  });

  componentRegistry.register({
    type: "shape",
    name: "形状",
    icon: "crop_square",
    description: "基础形状，矩形/圆形/线条",
    category: "basic",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 150 },
    defaultConfig: {
      shapeType: "rect",
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      borderRadius: 0,
    },
    capabilities: {
      resizable: true,
      rotatable: true,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/ShapeRenderer").then(m => ({ default: m.ShapeRenderer }))),
    configSchema: [
      { key: "shapeType", label: "形状类型", type: "select", options: [
        { label: "矩形", value: "rect" },
        { label: "圆形", value: "circle" },
        { label: "线条", value: "line" },
      ], group: "内容" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "stroke", label: "边框色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "样式" },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "样式" },
    ],
  });

  componentRegistry.register({
    type: "metric",
    name: "指标卡",
    icon: "speed",
    description: "数据驱动的指标显示组件，支持实时数值、单位、趋势和状态颜色",
    category: "chart",
    version: "2.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 120 },
    defaultConfig: {
      dataSourceId: "",
      field: "",
      title: "指标名称",
      value: "--",
      unit: "",
      precision: 1,
      prefix: "",
      suffix: "",
      showTrend: true,
      trend: "none",
      color: "#2196F3",
      titleColor: "rgba(255,255,255,0.5)",
      valueColor: "#2196F3",
      unitColor: "rgba(255,255,255,0.4)",
      fontSize: 28,
      titleFontSize: 11,
      backgroundColor: "rgba(0,0,0,0.2)",
      borderRadius: 4,
      padding: 12,
      statusRules: [],
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: true,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/MetricRenderer").then((m) => ({ default: m.MetricRenderer }))),
    events: [
      { id: "click", name: "点击" },
      { id: "valueChanged", name: "值变化" },
    ],
    actions: [
      { id: "updateData", name: "更新数据" },
      { id: "highlight", name: "高亮" },
    ],
    dataSchema: {
      sourceType: "api",
      apiConfig: {
        url: "",
        method: "GET",
      },
    },
    configSchema: [
      { key: "dataSourceId", label: "数据源", type: "datasource", group: "数据" },
      { key: "field", label: "数据字段", type: "datafield", group: "数据", hidden: (c) => !c.dataSourceId },
      { key: "title", label: "标题", type: "text", group: "显示" },
      { key: "unit", label: "单位", type: "text", group: "显示", placeholder: "如: °C, %, m/s" },
      { key: "precision", label: "小数位数", type: "number", group: "显示", min: 0, defaultValue: 1, hidden: (c) => !c.dataSourceId },
      { key: "prefix", label: "前缀", type: "text", group: "显示" },
      { key: "suffix", label: "后缀", type: "text", group: "显示" },
      { key: "showTrend", label: "显示趋势", type: "toggle", group: "显示" },
      { key: "color", label: "主题色", type: "color", group: "样式", defaultValue: "#2196F3" },
      { key: "valueColor", label: "数值颜色", type: "color", group: "样式", hidden: (c) => !c.valueColor },
      { key: "titleColor", label: "标题颜色", type: "color", group: "样式", hidden: (c) => !c.titleColor },
      { key: "fontSize", label: "数值字号", type: "number", group: "样式", min: 0, defaultValue: 28 },
      { key: "titleFontSize", label: "标题字号", type: "number", group: "样式", min: 0, defaultValue: 11 },
      { key: "backgroundColor", label: "背景色", type: "color", group: "样式" },
      { key: "borderRadius", label: "圆角", type: "number", group: "样式", min: 0, defaultValue: 4 },
      { key: "padding", label: "内边距", type: "number", group: "样式", min: 0, defaultValue: 12 },
      { key: "statusRules", label: "状态规则", type: "json", group: "高级", placeholder: '[{"min":0,"max":30,"color":"#4caf50","label":"正常"}]' },
    ],
  });

  componentRegistry.register({
    type: "video",
    name: "视频",
    icon: "videocam",
    description: "视频播放组件",
    category: "media",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 300 },
    defaultConfig: {
      source: "",
      autoplay: false,
      muted: true,
      controls: true,
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/VideoRenderer").then(m => ({ default: m.VideoRenderer }))),
    events: [
      { id: "play", name: "播放" },
      { id: "pause", name: "暂停" },
      { id: "ended", name: "结束" },
    ],
    actions: [
      { id: "play", name: "播放" },
      { id: "pause", name: "暂停" },
    ],
    configSchema: [
      { key: "source", label: "视频源", type: "text", group: "内容" },
      { key: "autoplay", label: "自动播放", type: "toggle", group: "播放" },
      { key: "muted", label: "静音", type: "toggle", group: "播放" },
      { key: "controls", label: "显示控件", type: "toggle", group: "播放" },
    ],
  });
}
