import { componentRegistry, lazy } from "./registryCore";
import { ANIMATION_SCHEMA, ANIMATION_DEFAULTS } from "./renderers/decorationAnimation";

export function registerDecorationComponents(): void {
  componentRegistry.register({
    type: "decoration-rect",
    name: "矩形",
    icon: "crop_square",
    description: "矩形装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 150 },
    defaultConfig: {
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      borderRadius: 0,
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: {
      resizable: true,
      rotatable: true,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/RectDecorationRenderer").then(m => ({ default: m.RectDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "样式" },
    ],
  });

  componentRegistry.register({
    type: "decoration-circle",
    name: "圆形",
    icon: "circle",
    description: "圆形装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 150, height: 150 },
    defaultConfig: {
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/CircleDecorationRenderer").then(m => ({ default: m.CircleDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
    ],
  });

  componentRegistry.register({
    type: "decoration-line",
    name: "线条",
    icon: "horizontal_rule",
    description: "线条装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 20 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 3,
      lineStyle: "solid",
      direction: "horizontal",
      opacity: 1,
    },
    capabilities: {
      resizable: true,
      rotatable: true,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/LineDecorationRenderer").then(m => ({ default: m.LineDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineStyle", label: "线型", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "水平", value: "horizontal" },
        { label: "垂直", value: "vertical" },
        { label: "左上-右下", value: "diagonal-tl-br" },
        { label: "右上-左下", value: "diagonal-tr-bl" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-arrow",
    name: "箭头",
    icon: "arrow_forward",
    description: "箭头装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 60 },
    defaultConfig: {
      color1: "#FF7BAC",
      color2: "#FF99C3",
      strokeWidth: 1,
      direction: "right",
      arrowType: "double",
      arrowSize: 10,
      arrowShape: "diamond",
      arrowCount: 3,
      lineStyle: "solid",
      opacity: 1,
    },
    capabilities: {
      resizable: true,
      rotatable: false,
      draggable: true,
      connectable: false,
      embeddable: false,
    },
    renderer: lazy(() => import("./renderers/ArrowDecorationRenderer").then(m => ({ default: m.ArrowDecorationRenderer }))),
    configSchema: [
      { key: "color1", label: "主色", type: "color", group: "样式" },
      { key: "color2", label: "副色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "向右", value: "right" },
        { label: "向左", value: "left" },
        { label: "向上", value: "up" },
        { label: "向下", value: "down" },
      ], group: "布局" },
      { key: "arrowShape", label: "箭头形状", type: "select", options: [
        { label: "菱形双向", value: "diamond" },
        { label: "三角箭头", value: "triangle" },
      ], group: "样式" },
      { key: "arrowType", label: "箭头类型", type: "select", options: [
        { label: "单向", value: "single" },
        { label: "双向", value: "double" },
        { label: "连续", value: "chain" },
      ], group: "样式" },
      { key: "arrowSize", label: "箭头大小", type: "number", min: 0, group: "样式" },
      { key: "arrowCount", label: "箭头数量", type: "number", min: 1, max: 10, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-ellipse",
    name: "椭圆",
    icon: "panorama_fish_eye",
    description: "椭圆装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 120 },
    defaultConfig: {
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/EllipseDecorationRenderer").then(m => ({ default: m.EllipseDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
    ],
  });

  componentRegistry.register({
    type: "decoration-triangle",
    name: "三角形",
    icon: "change_history",
    description: "三角形装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 150, height: 130 },
    defaultConfig: {
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      direction: "up",
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/TriangleDecorationRenderer").then(m => ({ default: m.TriangleDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "向上", value: "up" },
        { label: "向下", value: "down" },
        { label: "向左", value: "left" },
        { label: "向右", value: "right" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-polygon",
    name: "多边形",
    icon: "hexagon",
    description: "多边形装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 150, height: 150 },
    defaultConfig: {
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      sides: 6,
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/PolygonDecorationRenderer").then(m => ({ default: m.PolygonDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
      { key: "sides", label: "边数", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-star",
    name: "星形",
    icon: "star",
    description: "星形装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 150, height: 150 },
    defaultConfig: {
      fill: "rgba(255, 193, 7, 0.4)",
      stroke: "#FFC107",
      strokeWidth: 2,
      points: 5,
      innerRatio: 0.4,
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/StarDecorationRenderer").then(m => ({ default: m.StarDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
      { key: "points", label: "角数", type: "number", min: 0, group: "布局" },
      { key: "innerRatio", label: "内径比", type: "slider", min: 0.1, max: 0.9, step: 0.05, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-ring",
    name: "圆环",
    icon: "trip_origin",
    description: "圆环装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 120, height: 120 },
    defaultConfig: {
      stroke: "#2196F3",
      ringWidth: 6,
      borderStyle: "solid",
      fill: "none",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/RingDecorationRenderer").then(m => ({ default: m.RingDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "ringWidth", label: "环宽", type: "number", min: 0, group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "borderStyle", label: "线型", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "点划线", value: "dash-dot" },
      ], group: "样式" },
    ],
  });

  componentRegistry.register({
    type: "decoration-diamond",
    name: "菱形",
    icon: "diamond",
    description: "菱形装饰组件",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 150, height: 150 },
    defaultConfig: {
      fill: "rgba(33, 150, 243, 0.3)",
      stroke: "#2196F3",
      strokeWidth: 2,
      borderStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/DiamondDecorationRenderer").then(m => ({ default: m.DiamondDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "borderStyle", label: "边框样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
        { label: "无边框", value: "none" },
      ], group: "边框" },
    ],
  });

  componentRegistry.register({
    type: "decoration-cross",
    name: "十字",
    icon: "add",
    description: "十字/加号装饰组件",
    category: "decoration",
    version: "2.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 100, height: 100 },
    defaultConfig: {
      fill: "#2196F3",
      stroke: "transparent",
      strokeWidth: 0,
      thickness: 10,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/CrossDecorationRenderer").then(m => ({ default: m.CrossDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "thickness", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
    ],
  });

  componentRegistry.register({
    type: "decoration-divider",
    name: "分隔线",
    icon: "remove",
    description: "装饰性分隔线",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 20 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      style: "single",
      gap: 3,
      lineStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/DividerDecorationRenderer").then(m => ({ default: m.DividerDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "style", label: "样式", type: "select", options: [
        { label: "单线", value: "single" },
        { label: "双线", value: "double" },
        { label: "渐变", value: "gradient" },
      ], group: "样式" },
      { key: "gap", label: "双线间距", type: "number", min: 0, group: "样式", hidden: (c) => c.style !== "double" },
    ],
  });

  componentRegistry.register({
    type: "decoration-wave",
    name: "波浪线",
    icon: "waves",
    description: "装饰性波浪线",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 40 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      amplitude: 10,
      wavelength: 30,
      lineStyle: "solid",
      fill: "none",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/WaveDecorationRenderer").then(m => ({ default: m.WaveDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "amplitude", label: "振幅", type: "number", min: 0, group: "布局" },
      { key: "wavelength", label: "波长", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-dashed-box",
    name: "虚线框",
    icon: "check_box_outline_blank",
    description: "虚线边框区域",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 150 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      dashLength: 8,
      gapLength: 4,
      borderRadius: 0,
      fill: "none",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/DashedBoxDecorationRenderer").then(m => ({ default: m.DashedBoxDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "边框色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "dashLength", label: "线段长度", type: "number", min: 0, group: "样式" },
      { key: "gapLength", label: "间距", type: "number", min: 0, group: "样式" },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "样式" },
    ],
  });

  componentRegistry.register({
    type: "decoration-gradient",
    name: "渐变块",
    icon: "gradient",
    description: "渐变色块装饰",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 150 },
    defaultConfig: {
      gradientFrom: "#2196F3",
      gradientTo: "#FF9800",
      direction: "to-right",
      borderRadius: 0,
      stroke: "none",
      strokeWidth: 0,
      animated: false,
      speed: 3000,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/GradientDecorationRenderer").then(m => ({ default: m.GradientDecorationRenderer }))),
    configSchema: [
      { key: "gradientFrom", label: "起始色", type: "color", group: "颜色" },
      { key: "gradientTo", label: "终止色", type: "color", group: "颜色" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "从左到右", value: "to-right" },
        { label: "从右到左", value: "to-left" },
        { label: "从上到下", value: "to-bottom" },
        { label: "从下到上", value: "to-top" },
        { label: "左上到右下", value: "to-right-bottom" },
        { label: "径向", value: "radial" },
      ], group: "布局" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "样式" },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
      { key: "animated", label: "渐变动画", type: "toggle", group: "动画" },
      { key: "speed", label: "动画速度", type: "number", min: 0, group: "动画" },
    ],
  });

  componentRegistry.register({
    type: "decoration-corner",
    name: "角标",
    icon: "crop_free",
    description: "四角装饰标记",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 150 },
    defaultConfig: {
      stroke: "#2196F3",
      size: 15,
      strokeWidth: 2,
      position: "all",
      style: "bracket",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/CornerDecorationRenderer").then(m => ({ default: m.CornerDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "style", label: "样式", type: "select", options: [
        { label: "方括号", value: "bracket" },
        { label: "L形", value: "l-shape" },
      ], group: "布局" },
      { key: "size", label: "角标长度", type: "number", min: 0, group: "布局" },
      { key: "position", label: "位置", type: "select", options: [
        { label: "四角", value: "all" },
        { label: "左上", value: "top-left" },
        { label: "右上", value: "top-right" },
        { label: "左下", value: "bottom-left" },
        { label: "右下", value: "bottom-right" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-dot",
    name: "标记点",
    icon: "fiber_manual_record",
    description: "装饰性标记点，支持多种形状",
    category: "decoration",
    version: "2.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 30, height: 30 },
    defaultConfig: {
      fill: "#2196F3",
      stroke: "transparent",
      strokeWidth: 0,
      shape: "circle",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/DotDecorationRenderer").then(m => ({ default: m.DotDecorationRenderer }))),
    configSchema: [
      { key: "shape", label: "形状", type: "select", options: [
        { label: "圆形", value: "circle" },
        { label: "方形", value: "square" },
        { label: "三角形", value: "triangle" },
        { label: "菱形", value: "diamond" },
        { label: "十字", value: "cross" },
        { label: "星形", value: "star" },
      ], group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "stroke", label: "边框色", type: "color", group: "边框" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "边框" },
    ],
  });

  componentRegistry.register({
    type: "decoration-grid",
    name: "网格背景",
    icon: "grid_on",
    description: "网格图案背景",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 200 },
    defaultConfig: {
      stroke: "rgba(255,255,255,0.1)",
      strokeWidth: 1,
      spacing: 20,
      lineStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/GridDecorationRenderer").then(m => ({ default: m.GridDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "网格色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0, group: "样式" },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "spacing", label: "间距", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-diagonal",
    name: "斜线背景",
    icon: "line_style",
    description: "斜线填充图案",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 200 },
    defaultConfig: {
      stroke: "rgba(255,255,255,0.1)",
      strokeWidth: 1,
      spacing: 10,
      angle: 45,
      lineStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/DiagonalDecorationRenderer").then(m => ({ default: m.DiagonalDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "线条色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0, group: "样式" },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "spacing", label: "间距", type: "number", min: 0, group: "布局" },
      { key: "angle", label: "角度", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-dots-pattern",
    name: "点阵背景",
    icon: "blur_on",
    description: "点阵填充图案",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 200 },
    defaultConfig: {
      fill: "rgba(255,255,255,0.15)",
      dotSize: 2,
      spacing: 12,
      shape: "circle",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/DotsPatternDecorationRenderer").then(m => ({ default: m.DotsPatternDecorationRenderer }))),
    configSchema: [
      { key: "fill", label: "点色", type: "color", group: "样式" },
      { key: "shape", label: "形状", type: "select", options: [
        { label: "圆形", value: "circle" },
        { label: "方形", value: "square" },
        { label: "菱形", value: "diamond" },
      ], group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "dotSize", label: "点大小", type: "number", min: 0, group: "布局" },
      { key: "spacing", label: "间距", type: "number", min: 0, group: "布局" },
    ],
  });

  // ── Title Frame Components (geometry only, no text) ──

  // ── Title Input (bare input, no frame) ──

  componentRegistry.register({
    type: "title-input",
    name: "标题输入框",
    icon: "title",
    description: "标题文字输入，搭配「标题栏」组件使用",
    category: "decoration-title",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 250, height: 46 },
    minSize: { width: 40, height: 20 },
    defaultConfig: {
      content: "标题",
      fontSize: 18,
      fontFamily: "inherit",
      fontWeight: "normal",
      color: "#ffffff",
      textAlign: "center",
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/TitleInputRenderer").then((m) => ({ default: m.TitleInputRenderer }))),
    configSchema: [
      { key: "content", label: "标题内容", type: "text", group: "内容" },
      { key: "fontSize", label: "字号", type: "number", min: 8, step: 1, group: "排版" },
      { key: "fontFamily", label: "字体", type: "select", options: [
        { label: "默认", value: "inherit" },
        { label: "苹方", value: '"PingFang SC", sans-serif' },
        { label: "微软雅黑", value: '"Microsoft YaHei", sans-serif' },
        { label: "思源黑体", value: '"Source Han Sans CN", sans-serif' },
      ], group: "排版" },
      { key: "fontWeight", label: "字重", type: "select", options: [
        { label: "正常", value: "normal" },
        { label: "粗体", value: "bold" },
      ], group: "排版" },
      { key: "color", label: "文字颜色", type: "color", group: "样式" },
      { key: "textAlign", label: "对齐", type: "select", options: [
        { label: "左对齐", value: "left" },
        { label: "居中", value: "center" },
        { label: "右对齐", value: "right" },
      ], group: "排版" },
    ],
  });

  const titleFrameSharedSchema = [
    { key: "stroke", label: "框线颜色", type: "color" as const, group: "样式" },
    { key: "strokeWidth", label: "线宽", type: "number" as const, min: 0.5, group: "样式" },
    { key: "fillColor", label: "填充色", type: "color" as const, group: "样式" },
    { key: "fillOpacity", label: "填充透明度", type: "slider" as const, min: 0, step: 0.05, group: "样式", max: 1 },
    { key: "glowEnabled", label: "光晕", type: "toggle" as const, group: "光晕" },
    { key: "glowColor", label: "光晕颜色", type: "color" as const, group: "光晕", hidden: (c: any) => !c.glowEnabled },
    { key: "opacity", label: "整体透明度", type: "slider" as const, min: 0, step: 0.1, group: "样式", max: 1 },
    { key: "letterSpacing", label: "字间距", type: "number" as const, min: 0, step: 0.5, group: "排版" },
  ];

  componentRegistry.register({
    type: "decoration-title-tech-corner",
    name: "科技角标框",
    icon: "view_in_ar",
    description: "四角L形科技标题框，搭配文本组件使用",
    category: "decoration-title",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 42 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.05)",
      fillOpacity: 1,
      glowEnabled: false,
      glowColor: "#2196F3",
      cornerSize: 14,
      cornerOffset: 8,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/TechCornerTitleFrameRenderer").then(m => ({ default: m.TechCornerTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "cornerSize", label: "角标大小", type: "number", min: 0, group: "布局" },
      { key: "cornerOffset", label: "角标偏移", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-title-gradient-bar",
    name: "渐变底条框",
    icon: "linear_scale",
    description: "渐变底条标题框，搭配文本组件使用",
    category: "decoration-title",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 40 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.08)",
      fillOpacity: 1,
      glowEnabled: false,
      glowColor: "#2196F3",
      barPosition: "left",
      barWidth: 3,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/GradientBarTitleFrameRenderer").then(m => ({ default: m.GradientBarTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "barPosition", label: "色条位置", type: "select", options: [
        { label: "左侧", value: "left" },
        { label: "右侧", value: "right" },
        { label: "双侧", value: "both" },
      ], group: "布局" },
      { key: "barWidth", label: "色条宽度", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-title-left-indicator",
    name: "左侧指示框",
    icon: "format_align_left",
    description: "左侧竖条指示器标题框，搭配文本组件使用",
    category: "decoration-title",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 38 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.06)",
      fillOpacity: 1,
      glowEnabled: false,
      glowColor: "#2196F3",
      indicatorWidth: 4,
      paddingLeft: 16,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/LeftIndicatorTitleFrameRenderer").then(m => ({ default: m.LeftIndicatorTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "indicatorWidth", label: "指示器宽度", type: "number", min: 0, group: "布局" },
      { key: "paddingLeft", label: "左内距", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-title-center-diamond",
    name: "居中菱形框",
    icon: "diamond",
    description: "居中菱形翼线标题框，支持双线/空心菱形/装饰竖线/扫描动画/波纹/流光，搭配文本组件使用",
    category: "decoration-title",
    version: "4.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 56 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.05)",
      fillOpacity: 1,
      glowEnabled: false,
      glowColor: "#2196F3",
      diamondSizeX: 6,
      diamondSizeY: 10,
      diamondGap: 22,
      wingStyle: "double",
      diamondStyle: "filled",
      showDecoLine: true,
      decoLineLength: 14,
      animated: false,
      speed: 3000,
      opacity: 1,
      connectorStyle: "dots",
      foldStyle: "sharp",
      wingEndStyle: "none",
      diamondCross: false,
      diamondPulse: false,
      wingFlow: false,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/CenterDiamondTitleFrameRenderer").then(m => ({ default: m.CenterDiamondTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "wingStyle", label: "翼线数量", type: "select", options: [
        { label: "单线", value: "single" },
        { label: "双线", value: "double" },
      ], group: "布局" },
      { key: "diamondStyle", label: "菱形样式", type: "select", options: [
        { label: "实心", value: "filled" },
        { label: "空心", value: "outlined" },
        { label: "双层", value: "double" },
      ], group: "布局" },
      { key: "diamondSizeX", label: "菱形宽度", type: "number", min: 0, step: 1, group: "布局" },
      { key: "diamondSizeY", label: "菱形高度", type: "number", min: 0, step: 1, group: "布局" },
      { key: "diamondGap", label: "菱形间距", type: "number", min: 0, step: 1, group: "布局" },
      { key: "connectorStyle", label: "中间连接", type: "select", options: [
        { label: "点阵", value: "dots" },
        { label: "虚线", value: "dashed" },
        { label: "细线", value: "thin" },
        { label: "渐变线", value: "gradient" },
      ], group: "布局" },
      { key: "foldStyle", label: "折角样式", type: "select", options: [
        { label: "尖角", value: "sharp" },
        { label: "圆角", value: "round" },
        { label: "直角", value: "square" },
        { label: "无", value: "none" },
      ], group: "布局" },
      { key: "wingEndStyle", label: "翼线端点", type: "select", options: [
        { label: "无", value: "none" },
        { label: "箭头", value: "arrow" },
        { label: "三角", value: "triangle" },
        { label: "圆点", value: "dot" },
      ], group: "布局" },
      { key: "showDecoLine", label: "装饰竖线", type: "toggle", group: "装饰" },
      { key: "decoLineLength", label: "竖线长度", type: "number", min: 0, group: "装饰", hidden: (c: any) => !c.showDecoLine },
      { key: "diamondCross", label: "菱形十字纹", type: "toggle", group: "装饰" },
      { key: "animated", label: "光脉冲动画", type: "toggle", group: "动画" },
      { key: "speed", label: "动画速度(ms)", type: "number", min: 0, group: "动画", hidden: (c: any) => !c.animated && !c.diamondPulse && !c.wingFlow },
      { key: "diamondPulse", label: "菱形波纹", type: "toggle", group: "动画" },
      { key: "wingFlow", label: "翼线流光", type: "toggle", group: "动画" },
    ],
  });

  componentRegistry.register({
    type: "decoration-title-double-wing",
    name: "双翼展开框",
    icon: "flight",
    description: "双翼展开标题框，翼从中心向两侧舒展，搭配文本组件使用",
    category: "decoration-title",
    version: "3.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 42 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.08)",
      fillOpacity: 1,
      glowEnabled: false,
      glowColor: "#2196F3",
      wingSpread: 16,
      wingWidth: 150,
      wingCurve: "angular",
      centerAnchor: "diamond",
      wingTipStyle: "arrow",
      innerLine: true,
      wingGlow: true,
      centerPulse: true,
      wingFlow: true,
      scanLine: false,
      speed: 3000,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/DoubleWingTitleFrameRenderer").then(m => ({ default: m.DoubleWingTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "wingSpread", label: "翼展幅", type: "number", min: 0, group: "布局" },
      { key: "wingWidth", label: "翼宽度", type: "number", min: 0, group: "布局" },
      { key: "wingCurve", label: "翼曲线", type: "select", options: [
        { label: "柔和", value: "gentle" },
        { label: "张力", value: "dramatic" },
        { label: "折线", value: "angular" },
        { label: "俯冲", value: "swoop" },
      ], group: "布局" },
      { key: "centerAnchor", label: "中心锚点", type: "select", options: [
        { label: "菱形", value: "diamond" },
        { label: "竖线", value: "line" },
        { label: "圆点", value: "dot" },
        { label: "十字", value: "cross" },
        { label: "无", value: "none" },
      ], group: "布局" },
      { key: "wingTipStyle", label: "翼端装饰", type: "select", options: [
        { label: "箭头", value: "arrow" },
        { label: "散射", value: "flare" },
        { label: "圆点", value: "dot" },
        { label: "菱形", value: "diamond" },
        { label: "无", value: "none" },
      ], group: "布局" },
      { key: "innerLine", label: "内线", type: "toggle", group: "装饰" },
      { key: "wingGlow", label: "发光", type: "toggle", group: "装饰" },
      { key: "centerPulse", label: "中心脉冲", type: "toggle", group: "动画" },
      { key: "wingFlow", label: "翼流光", type: "toggle", group: "动画" },
      { key: "scanLine", label: "扫描线", type: "toggle", group: "动画" },
      { key: "speed", label: "动画速度(ms)", type: "number", min: 0, group: "动画", hidden: (c: any) => !c.centerPulse && !c.wingFlow && !c.scanLine },
    ],
  });

  componentRegistry.register({
    type: "decoration-title-underline",
    name: "底部光线框",
    icon: "horizontal_rule",
    description: "底部渐变光线标题框，搭配文本组件使用",
    category: "decoration-title",
    version: "2.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 42 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.06)",
      fillOpacity: 1,
      glowEnabled: true,
      glowColor: "#2196F3",
      opacity: 1,
      lineStyle: "gradient",
      endCapStyle: "none",
      centerDecor: "diamond",
      linePosition: 0,
      lineLength: 96,
      decorSize: 100,
      glowPulse: true,
      flowLight: true,
      speed: 3000,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/UnderlineTitleFrameRenderer").then(m => ({ default: m.UnderlineTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "linePosition", label: "光线位置", type: "number", min: 0, step: 1, group: "布局" },
      { key: "lineLength", label: "光线长度", type: "slider", min: 10, max: 100, step: 1, group: "布局" },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "渐变", value: "gradient" },
        { label: "光束", value: "beam" },
        { label: "脉冲", value: "pulse" },
        { label: "双线", value: "double" },
        { label: "单色", value: "single" },
        { label: "虚线", value: "dashed" },
      ], group: "装饰" },
      { key: "endCapStyle", label: "端点样式", type: "select", options: [
        { label: "无", value: "none" },
        { label: "光点", value: "glow" },
        { label: "散射", value: "flare" },
        { label: "圆点", value: "dot" },
        { label: "菱形", value: "diamond" },
        { label: "箭头", value: "arrow" },
      ], group: "装饰" },
      { key: "centerDecor", label: "中心装饰", type: "select", options: [
        { label: "菱形", value: "diamond" },
        { label: "光环", value: "ring" },
        { label: "星芒", value: "star" },
        { label: "圆点", value: "dot" },
        { label: "十字", value: "cross" },
        { label: "短线", value: "shortLine" },
        { label: "无", value: "none" },
      ], group: "装饰" },
      { key: "decorSize", label: "装饰大小", type: "slider", min: 30, max: 300, step: 5, group: "装饰" },
      { key: "glowPulse", label: "光晕脉冲", type: "toggle", group: "动画" },
      { key: "flowLight", label: "流光效果", type: "toggle", group: "动画" },
      { key: "speed", label: "动画速度", type: "number", min: 500, step: 100, group: "动画" },
    ],
  });

  componentRegistry.register({
    type: "decoration-title-top-glow",
    name: "顶部光带框",
    icon: "wb_sunny",
    description: "顶部光带标题框，搭配文本组件使用",
    category: "decoration-title",
    version: "2.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 400, height: 40 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      fillColor: "rgba(33, 150, 243, 0.06)",
      fillOpacity: 1,
      glowEnabled: true,
      glowColor: "#2196F3",
      opacity: 1,
      lineStyle: "gradient",
      endCapStyle: "none",
      centerDecor: "diamond",
      linePosition: 0,
      lineLength: 96,
      decorSize: 100,
      glowPulse: true,
      flowLight: true,
      speed: 3000,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/TopGlowTitleFrameRenderer").then(m => ({ default: m.TopGlowTitleFrameRenderer }))),
    configSchema: [
      ...titleFrameSharedSchema,
      { key: "linePosition", label: "光线位置", type: "number", min: 0, step: 1, group: "布局" },
      { key: "lineLength", label: "光线长度", type: "slider", min: 10, max: 100, step: 1, group: "布局" },
      { key: "lineStyle", label: "线条样式", type: "select", options: [
        { label: "渐变", value: "gradient" },
        { label: "光束", value: "beam" },
        { label: "脉冲", value: "pulse" },
        { label: "双线", value: "double" },
        { label: "单色", value: "single" },
        { label: "虚线", value: "dashed" },
      ], group: "装饰" },
      { key: "endCapStyle", label: "端点样式", type: "select", options: [
        { label: "无", value: "none" },
        { label: "光点", value: "glow" },
        { label: "散射", value: "flare" },
        { label: "圆点", value: "dot" },
        { label: "菱形", value: "diamond" },
        { label: "箭头", value: "arrow" },
      ], group: "装饰" },
      { key: "centerDecor", label: "中心装饰", type: "select", options: [
        { label: "菱形", value: "diamond" },
        { label: "光环", value: "ring" },
        { label: "星芒", value: "star" },
        { label: "圆点", value: "dot" },
        { label: "十字", value: "cross" },
        { label: "短线", value: "shortLine" },
        { label: "无", value: "none" },
      ], group: "装饰" },
      { key: "decorSize", label: "装饰大小", type: "slider", min: 30, max: 300, step: 5, group: "装饰" },
      { key: "glowPulse", label: "光晕脉冲", type: "toggle", group: "动画" },
      { key: "flowLight", label: "流光效果", type: "toggle", group: "动画" },
      { key: "speed", label: "动画速度", type: "number", min: 500, step: 100, group: "动画" },
    ],
  });

  componentRegistry.register({
    type: "decoration-tech-border",
    name: "科技边框",
    icon: "view_in_ar",
    description: "科技感边框，支持角标/全框/双线风格",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 200 },
    defaultConfig: {
      stroke: "#2196F3",
      fill: "rgba(33, 150, 243, 0.05)",
      strokeWidth: 1.5,
      cornerSize: 15,
      style: "corner",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/TechBorderDecorationRenderer").then(m => ({ default: m.TechBorderDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0.5, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "cornerSize", label: "角标大小", type: "number", min: 0, group: "布局" },
      { key: "style", label: "风格", type: "select", options: [
        { label: "角标", value: "corner" },
        { label: "全框", value: "full" },
        { label: "双线", value: "double" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-panel",
    name: "面板容器",
    icon: "dashboard",
    description: "带标题栏的面板容器",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 250 },
    defaultConfig: {
      stroke: "#2196F3",
      fill: "rgba(33, 150, 243, 0.05)",
      strokeWidth: 1.5,
      title: "面板",
      fontSize: 12,
      cornerSize: 12,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/PanelDecorationRenderer").then(m => ({ default: m.PanelDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0.5, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "title", label: "标题", type: "text", group: "内容" },
      { key: "fontSize", label: "字号", type: "number", min: 0, group: "内容" },
      { key: "cornerSize", label: "角标大小", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-metric-card",
    name: "指标卡",
    icon: "speed",
    description: "数据指标展示卡片",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 180, height: 120 },
    defaultConfig: {
      stroke: "#2196F3",
      fill: "rgba(33, 150, 243, 0.08)",
      strokeWidth: 1,
      value: "1,234",
      label: "指标名称",
      unit: "",
      valueSize: 28,
      labelSize: 10,
      trend: "none",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/MetricCardDecorationRenderer").then(m => ({ default: m.MetricCardDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "value", label: "数值", type: "text", group: "内容" },
      { key: "label", label: "标签", type: "text", group: "内容" },
      { key: "unit", label: "单位", type: "text", group: "内容" },
      { key: "valueSize", label: "数值字号", type: "number", min: 0, group: "内容" },
      { key: "labelSize", label: "标签字号", type: "number", min: 0, group: "内容" },
      { key: "trend", label: "趋势", type: "select", options: [
        { label: "无", value: "none" },
        { label: "上升", value: "up" },
        { label: "下降", value: "down" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-ornamental-divider",
    name: "装饰分割线",
    icon: "line_style",
    description: "带装饰元素的分割线，支持菱形/圆点/箭头",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 30 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      text: "",
      style: "diamond",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/OrnamentalDividerDecorationRenderer").then(m => ({ default: m.OrnamentalDividerDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "text", label: "中间文字", type: "text", group: "内容" },
      { key: "style", label: "装饰样式", type: "select", options: [
        { label: "菱形", value: "diamond" },
        { label: "圆点", value: "dot" },
        { label: "箭头", value: "arrow" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-progress-bar",
    name: "进度条",
    icon: "show_chart",
    description: "水平/垂直进度条",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 250, height: 30 },
    defaultConfig: {
      stroke: "#2196F3",
      trackColor: "rgba(255,255,255,0.1)",
      strokeWidth: 8,
      progress: 60,
      direction: "horizontal",
      showLabel: true,
      borderRadius: 4,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/ProgressBarDecorationRenderer").then(m => ({ default: m.ProgressBarDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "进度色", type: "color", group: "样式" },
      { key: "trackColor", label: "轨道色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "条宽", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "progress", label: "进度", type: "slider", min: 0, step: 1, group: "内容", max: 100 },
      { key: "showLabel", label: "显示标签", type: "toggle", group: "内容" },
      { key: "borderRadius", label: "圆角", type: "number", min: 0, group: "布局" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "水平", value: "horizontal" },
        { label: "垂直", value: "vertical" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-status-light",
    name: "状态指示灯",
    icon: "fiber_manual_record",
    description: "状态指示灯，支持多种状态颜色",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 30, height: 30 },
    defaultConfig: {
      status: "normal",
      size: 20,
      showLabel: false,
      label: "",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/StatusLightDecorationRenderer").then(m => ({ default: m.StatusLightDecorationRenderer }))),
    configSchema: [
      { key: "status", label: "状态", type: "select", options: [
        { label: "正常", value: "normal" },
        { label: "警告", value: "warning" },
        { label: "错误", value: "error" },
        { label: "信息", value: "info" },
        { label: "关闭", value: "off" },
      ], group: "内容" },
      { key: "size", label: "大小", type: "number", min: 0, group: "样式" },
      { key: "showLabel", label: "显示标签", type: "toggle", group: "内容" },
      { key: "label", label: "标签文字", type: "text", group: "内容" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
    ],
  });

  componentRegistry.register({
    type: "decoration-number-badge",
    name: "装饰编号",
    icon: "format_list_numbered",
    description: "带编号的装饰徽章，支持多种形状",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 50, height: 50 },
    defaultConfig: {
      stroke: "#2196F3",
      fill: "#2196F3",
      text: "1",
      fontSize: 14,
      shape: "circle",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/NumberBadgeDecorationRenderer").then(m => ({ default: m.NumberBadgeDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "边框色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "text", label: "编号", type: "text", group: "内容" },
      { key: "fontSize", label: "字号", type: "number", min: 0, group: "内容" },
      { key: "shape", label: "形状", type: "select", options: [
        { label: "圆形", value: "circle" },
        { label: "方形", value: "square" },
        { label: "菱形", value: "diamond" },
        { label: "六边形", value: "hexagon" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-badge",
    name: "标签徽章",
    icon: "label",
    description: "标签徽章，支持圆角/药丸/标签/直角风格",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 100, height: 40 },
    defaultConfig: {
      stroke: "#2196F3",
      fill: "rgba(33, 150, 243, 0.2)",
      text: "标签",
      fontSize: 11,
      style: "rounded",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/BadgeDecorationRenderer").then(m => ({ default: m.BadgeDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "边框色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "text", label: "文字", type: "text", group: "内容" },
      { key: "fontSize", label: "字号", type: "number", min: 0, group: "内容" },
      { key: "style", label: "风格", type: "select", options: [
        { label: "圆角", value: "rounded" },
        { label: "药丸", value: "pill" },
        { label: "标签", value: "tag" },
        { label: "直角", value: "sharp" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-line-cap",
    name: "装饰端帽",
    icon: "linear_scale",
    description: "带装饰端帽的线条",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 30 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      capStyle: "diamond",
      lineStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/LineCapDecorationRenderer").then(m => ({ default: m.LineCapDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineStyle", label: "线型", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "capStyle", label: "端帽样式", type: "select", options: [
        { label: "箭头", value: "arrow" },
        { label: "圆形", value: "circle" },
        { label: "方形", value: "square" },
        { label: "菱形", value: "diamond" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-light-beam",
    name: "光束",
    icon: "flare",
    description: "带光晕的光束效果",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 60 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 3,
      direction: "horizontal",
      beamWidth: 30,
      animated: true,
      speed: 3000,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: true, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/LightBeamDecorationRenderer").then(m => ({ default: m.LightBeamDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "beamWidth", label: "光束宽度", type: "number", min: 0, group: "布局" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "水平", value: "horizontal" },
        { label: "垂直", value: "vertical" },
        { label: "对角", value: "diagonal" },
      ], group: "布局" },
      { key: "animated", label: "光束动画", type: "toggle", group: "动画" },
      { key: "speed", label: "动画速度(ms)", type: "number", min: 0, group: "动画" },
    ],
  });

  componentRegistry.register({
    type: "decoration-scan-line",
    name: "扫描线",
    icon: "view_stream",
    description: "扫描线效果背景",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 200 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      direction: "horizontal",
      lineCount: 5,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/ScanLineDecorationRenderer").then(m => ({ default: m.ScanLineDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0.5, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineCount", label: "线条数量", type: "number", min: 0, group: "布局" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "水平", value: "horizontal" },
        { label: "垂直", value: "vertical" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-particle",
    name: "粒子点",
    icon: "blur_on",
    description: "随机粒子点效果",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 200, height: 200 },
    defaultConfig: {
      stroke: "#2196F3",
      particleCount: 20,
      minSize: 1,
      maxSize: 4,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/ParticleDecorationRenderer").then(m => ({ default: m.ParticleDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "particleCount", label: "粒子数量", type: "number", min: 0, group: "布局" },
      { key: "minSize", label: "最小尺寸", type: "number", min: 0.5, group: "布局" },
      { key: "maxSize", label: "最大尺寸", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-pulse-ring",
    name: "呼吸环",
    icon: "radio_button_checked",
    description: "多层呼吸环效果",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 120, height: 120 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      ringCount: 3,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/PulseRingDecorationRenderer").then(m => ({ default: m.PulseRingDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "ringCount", label: "环数", type: "number", min: 0, group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-data-flow",
    name: "数据流",
    icon: "waves",
    description: "数据流动曲线效果",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 100 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 1.5,
      direction: "horizontal",
      lineCount: 5,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/DataFlowDecorationRenderer").then(m => ({ default: m.DataFlowDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0.5, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineCount", label: "线条数量", type: "number", min: 0, group: "布局" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "水平", value: "horizontal" },
        { label: "垂直", value: "vertical" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-timeline",
    name: "时间线",
    icon: "timeline",
    description: "时间线装饰，支持水平/垂直方向",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 300, height: 30 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      nodeCount: 3,
      direction: "horizontal",
      nodeStyle: "circle",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/TimelineDecorationRenderer").then(m => ({ default: m.TimelineDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "线宽", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "nodeCount", label: "节点数", type: "number", min: 0, group: "布局" },
      { key: "direction", label: "方向", type: "select", options: [
        { label: "水平", value: "horizontal" },
        { label: "垂直", value: "vertical" },
      ], group: "布局" },
      { key: "nodeStyle", label: "节点样式", type: "select", options: [
        { label: "圆形", value: "circle" },
        { label: "菱形", value: "diamond" },
        { label: "方形", value: "square" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-map-marker",
    name: "地图标记",
    icon: "place",
    description: "地图标记点，支持图钉/圆形/菱形",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 40, height: 50 },
    defaultConfig: {
      stroke: "#F44336",
      fill: "#F44336",
      strokeWidth: 1.5,
      markerStyle: "pin",
      label: "",
      fontSize: 10,
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/MapMarkerDecorationRenderer").then(m => ({ default: m.MapMarkerDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "边框色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "边框宽度", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "label", label: "标记文字", type: "text", group: "内容" },
      { key: "fontSize", label: "字号", type: "number", min: 0, group: "内容" },
      { key: "markerStyle", label: "样式", type: "select", options: [
        { label: "图钉", value: "pin" },
        { label: "圆形", value: "circle" },
        { label: "菱形", value: "diamond" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-connector",
    name: "连接线",
    icon: "trending_flat",
    description: "组件间连接线，支持直线/折线/曲线/阶梯",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 150, height: 100 },
    defaultConfig: {
      stroke: "#2196F3",
      strokeWidth: 2,
      connectorStyle: "straight",
      lineStyle: "solid",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/ConnectorDecorationRenderer").then(m => ({ default: m.ConnectorDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "颜色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "粗细", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "lineStyle", label: "线型", type: "select", options: [
        { label: "实线", value: "solid" },
        { label: "虚线", value: "dashed" },
        { label: "点线", value: "dotted" },
      ], group: "样式" },
      { key: "connectorStyle", label: "连接样式", type: "select", options: [
        { label: "直线", value: "straight" },
        { label: "折线", value: "elbow" },
        { label: "曲线", value: "curve" },
        { label: "阶梯", value: "step" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-ribbon",
    name: "装饰丝带",
    icon: "bookmark",
    description: "角落丝带标签",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 120, height: 120 },
    defaultConfig: {
      stroke: "#2196F3",
      fill: "#2196F3",
      text: "标签",
      fontSize: 11,
      position: "top-left",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: true },
    renderer: lazy(() => import("./renderers/RibbonDecorationRenderer").then(m => ({ default: m.RibbonDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "边框色", type: "color", group: "样式" },
      { key: "fill", label: "填充色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "text", label: "文字", type: "text", group: "内容" },
      { key: "fontSize", label: "字号", type: "number", min: 0, group: "内容" },
      { key: "position", label: "位置", type: "select", options: [
        { label: "左上", value: "top-left" },
        { label: "右上", value: "top-right" },
        { label: "左下", value: "bottom-left" },
        { label: "右下", value: "bottom-right" },
      ], group: "布局" },
    ],
  });

  componentRegistry.register({
    type: "decoration-circular-progress",
    name: "环形进度",
    icon: "donut_large",
    description: "环形进度指示器",
    category: "decoration",
    version: "1.0.0",
    builtIn: true,
    enabled: true,
    defaultSize: { width: 120, height: 120 },
    defaultConfig: {
      stroke: "#2196F3",
      trackColor: "rgba(255,255,255,0.1)",
      strokeWidth: 6,
      progress: 60,
      showLabel: true,
      label: "",
      opacity: 1,
    },
    capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
    renderer: lazy(() => import("./renderers/CircularProgressDecorationRenderer").then(m => ({ default: m.CircularProgressDecorationRenderer }))),
    configSchema: [
      { key: "stroke", label: "进度色", type: "color", group: "样式" },
      { key: "trackColor", label: "轨道色", type: "color", group: "样式" },
      { key: "strokeWidth", label: "环宽", type: "number", min: 0, group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, step: 0.1, group: "样式", max: 1 },
      { key: "progress", label: "进度", type: "slider", min: 0, step: 1, group: "内容", max: 100 },
      { key: "showLabel", label: "显示标签", type: "toggle", group: "内容" },
      { key: "label", label: "标签文字", type: "text", group: "内容" },
    ],
  });

  const datavBorderMeta: Array<{ idx: number; name: string; desc: string; icon: string; defaultSize: { width: number; height: number }; minSize: { width: number; height: number }; defaultColors: [string, string]; hasReverse: boolean; hasDur: boolean; durDefault?: number }> = [
    { idx: 1, name: "科技感角标边框", desc: "科技感角标边框", icon: "crop_free", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#4fd2dd", "#235fa7"], hasReverse: false, hasDur: false },
    { idx: 2, name: "线段角标边框", desc: "线段角标边框", icon: "check_box_outline_blank", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#fff", "rgba(255,255,255,0.6)"], hasReverse: false, hasDur: false },
    { idx: 3, name: "渐变线段边框", desc: "渐变线段边框", icon: "gradient", defaultSize: { width: 400, height: 300 }, minSize: { width: 80, height: 80 }, defaultColors: ["#2862b7", "#2862b7"], hasReverse: false, hasDur: false },
    { idx: 4, name: "流星边框", desc: "流星边框", icon: "flare", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["red", "rgba(0,0,255,0.8)"], hasReverse: true, hasDur: false },
    { idx: 5, name: "切角边框", desc: "切角边框", icon: "crop_square", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["rgba(255,255,255,0.35)", "rgba(255,255,255,0.20)"], hasReverse: true, hasDur: false },
    { idx: 6, name: "三角角标边框", desc: "三角角标边框", icon: "change_history", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["rgba(255,255,255,0.35)", "gray"], hasReverse: false, hasDur: false },
    { idx: 7, name: "光晕边框", desc: "光晕边框", icon: "blur_on", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["rgba(128,128,128,0.3)", "rgba(128,128,128,0.5)"], hasReverse: false, hasDur: false },
    { idx: 8, name: "流光边框", desc: "流光边框", icon: "linear_scale", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#235fa7", "#4fd2dd"], hasReverse: true, hasDur: true, durDefault: 3 },
    { idx: 9, name: "微光边框", desc: "微光边框", icon: "gradient", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#11eefd", "#0078d2"], hasReverse: false, hasDur: false },
    { idx: 10, name: "钻石角标边框", desc: "钻石角标边框", icon: "diamond", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#1d48c4", "#d3e1f8"], hasReverse: false, hasDur: false },
    { idx: 11, name: "金箔雕花边框", desc: "四周带雕花卷曲装饰的标题边框（继承自 SVG 参考，标题位置可灵活调整）", icon: "auto_awesome", defaultSize: { width: 500, height: 320 }, minSize: { width: 240, height: 180 }, defaultColors: ["#e1b86c", "#8c5c00"], hasReverse: true, hasDur: false },
    { idx: 12, name: "扫描边框", desc: "扫描边框", icon: "view_stream", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#2e6099", "#7ce7fd"], hasReverse: false, hasDur: false },
    { idx: 13, name: "折线角标边框", desc: "折线角标边框", icon: "show_chart", defaultSize: { width: 400, height: 300 }, minSize: { width: 100, height: 80 }, defaultColors: ["#6586ec", "#2cf7fe"], hasReverse: false, hasDur: false },
  ];

  const datavDecoMeta: Array<{ idx: number; name: string; desc: string; icon: string; defaultSize: { width: number; height: number }; minSize: { width: number; height: number }; defaultColors: [string, string]; hasReverse: boolean; hasDur: boolean; durDefault?: number; hasScanDur?: boolean }> = [
    { idx: 1, name: "点阵装饰", desc: "点阵装饰", icon: "blur_on", defaultSize: { width: 400, height: 50 }, minSize: { width: 100, height: 30 }, defaultColors: ["#fff", "#0de7c2"], hasReverse: false, hasDur: false },
    { idx: 2, name: "扫描线装饰", desc: "扫描线装饰", icon: "linear_scale", defaultSize: { width: 400, height: 6 }, minSize: { width: 60, height: 4 }, defaultColors: ["#3faacb", "#fff"], hasReverse: true, hasDur: true, durDefault: 6 },
    { idx: 3, name: "闪烁点阵装饰", desc: "闪烁点阵装饰", icon: "grid_on", defaultSize: { width: 400, height: 35 }, minSize: { width: 100, height: 20 }, defaultColors: ["#7acaec", "transparent"], hasReverse: false, hasDur: false },
    { idx: 4, name: "渐变边框装饰", desc: "渐变边框装饰", icon: "gradient", defaultSize: { width: 400, height: 300 }, minSize: { width: 20, height: 60 }, defaultColors: ["rgba(255,255,255,0.3)", "rgba(255,255,255,0.3)"], hasReverse: true, hasDur: true, durDefault: 3 },
    { idx: 5, name: "折线装饰", desc: "折线装饰", icon: "show_chart", defaultSize: { width: 400, height: 60 }, minSize: { width: 100, height: 30 }, defaultColors: ["#3f96a5", "#3f96a5"], hasReverse: false, hasDur: true, durDefault: 1.2 },
    { idx: 6, name: "柱状跳动装饰", desc: "柱状跳动装饰", icon: "bar_chart", defaultSize: { width: 400, height: 35 }, minSize: { width: 100, height: 20 }, defaultColors: ["#7acaec", "#7acaec"], hasReverse: false, hasDur: false },
    { idx: 7, name: "双翼装饰", desc: "双翼装饰（左右对角张开 + 中间弧形带）", icon: "arrow_outward", defaultSize: { width: 540, height: 180 }, minSize: { width: 360, height: 120 }, defaultColors: ["#FF0000", "#750000"], hasReverse: false, hasDur: false },
    { idx: 8, name: "缠枝纹饰带", desc: "缠枝纹饰带（徽章形双环 + 四角缠枝纹）", icon: "change_history", defaultSize: { width: 300, height: 50 }, minSize: { width: 60, height: 30 }, defaultColors: ["#C89F49", "#C89F49"], hasReverse: true, hasDur: false },
    { idx: 9, name: "流光飘带", desc: "流光飘带（细弧放射 + 金色渐变上下水流动）", icon: "auto_awesome", defaultSize: { width: 300, height: 450 }, minSize: { width: 120, height: 180 }, defaultColors: ["#8C5C00", "#FFE680"], hasReverse: false, hasDur: true, durDefault: 3 },
    { idx: 10, name: "雕花边框", desc: "雕花边框（4 角花 + 左/右各 3 边花，矩形装饰）", icon: "auto_awesome_motion", defaultSize: { width: 300, height: 450 }, minSize: { width: 120, height: 180 }, defaultColors: ["#00AEEF", "rgba(0,174,239,0.3)"], hasReverse: false, hasDur: false },
    { idx: 11, name: "金色卷草花纹边框", desc: "金色卷草花纹边框（对角线 L 形饰带 + 右上左下卷草花纹，参考古典金箔雕花风格）", icon: "auto_awesome", defaultSize: { width: 400, height: 300 }, minSize: { width: 80, height: 40 }, defaultColors: ["#C89F49", "#8c5c00"], hasReverse: true, hasDur: false },
    { idx: 12, name: "雷达装饰", desc: "雷达装饰", icon: "trip_origin", defaultSize: { width: 200, height: 200 }, minSize: { width: 80, height: 80 }, defaultColors: ["#2783ce", "#2cf7fe"], hasReverse: false, hasDur: false, hasScanDur: true },
  ];

  for (const meta of datavBorderMeta) {
    const color1Label = meta.idx === 7 ? "主色(光晕+边框+外角)" : meta.idx === 8 ? "主色(静态底边)" : meta.idx === 9 ? "主色(渐变深底)" : "主色";
    const color2Label = meta.idx === 7 ? "副色(内角)" : meta.idx === 8 ? "副色(流光高亮)" : meta.idx === 9 ? "副色(渐变高光)" : "副色";
    const schema: any[] = [
      { key: "color1", label: color1Label, type: "color", group: "样式" },
      { key: "color2", label: color2Label, type: "color", group: "样式" },
      { key: "backgroundColor", label: "背景色", type: "color", group: "样式" },
      { key: "opacity", label: "透明度", type: "slider", min: 0, max: 1, step: 0.05, group: "样式" },
      ...([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].includes(meta.idx) ? [] : [{ key: "strokeWidth", label: "线条粗细", type: "slider", min: 0.5, max: 100, step: 2, group: "样式" }]),
      { key: "padding", label: "内边距", type: "slider", min: 0, max: 60, step: 2, group: "布局" },
    ];
    if (meta.hasReverse) schema.push({ key: "reverse", label: meta.idx === 8 ? "反转追光方向" : "反转方向", type: "toggle", group: "布局" });
    if (meta.hasDur) schema.push({ key: "dur", label: meta.idx === 8 ? "流光周期(秒)" : "动画时长(秒)", type: "number", min: 0.5, step: 0.5, group: "动画" });
    schema.push({ key: "borderRadius", label: "圆角", type: "number", min: 0, max: 40, step: 1, group: "布局" });

    componentRegistry.register({
      type: `datav-border-${meta.idx}`,
      name: meta.name,
      icon: meta.icon,
      description: meta.desc,
      category: "datav",
      version: "1.0.0",
      builtIn: true,
      enabled: true,
      defaultSize: meta.defaultSize,
      minSize: meta.minSize,
      defaultConfig: {
        datavKind: "border",
        datavIndex: meta.idx,
        color1: meta.defaultColors[0],
        color2: meta.defaultColors[1],
        backgroundColor: "transparent",
        opacity: 1,
        strokeWidth: 1,
        padding: 0,
        borderRadius: 0,
        reverse: false,
        dur: meta.durDefault ?? 3,
      },
      capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
      renderer: lazy(() => import("./renderers/DataVRenderer").then(m => ({ default: m.DataVRenderer }))),
      configSchema: schema,
    });
  }

  for (const meta of datavDecoMeta) {
      const colorSchema: any[] = [
        { key: "color1", label: "主色", type: "color", group: "样式" },
        { key: "color2", label: "副色", type: "color", group: "样式" },
      ];
    const schema: any[] = [
      ...colorSchema,
      { key: "opacity", label: "透明度", type: "slider", min: 0, max: 1, step: 0.05, group: "样式" },
      { key: "strokeWidth", label: "线条粗细", type: "slider", min: 0.5, max: 100, step: 2, group: "样式" },
    ];
    if (meta.hasReverse) schema.push({ key: "reverse", label: "反转方向", type: "toggle", group: "布局" });
    if (meta.hasDur) schema.push({ key: "dur", label: "动画时长(秒)", type: "number", min: 0.5, step: 0.5, group: "动画" });
    if (meta.hasScanDur) {
      schema.push({ key: "scanDur", label: "扫描时长(秒)", type: "number", min: 0.5, step: 0.5, group: "动画" });
      schema.push({ key: "haloDur", label: "光晕时长(秒)", type: "number", min: 0.5, step: 0.5, group: "动画" });
    }
    schema.push({ key: "borderRadius", label: "圆角", type: "number", min: 0, max: 40, step: 1, group: "布局" });

    const defaultConfig: Record<string, any> = {
      datavKind: "decoration",
      datavIndex: meta.idx,
      opacity: 1,
      strokeWidth: 1,
      borderRadius: 0,
      reverse: false,
      dur: meta.durDefault ?? 3,
    };
    /* 写入 color1/color2 */
    defaultConfig.color1 = meta.defaultColors[0];
    defaultConfig.color2 = meta.defaultColors[1];
    if (meta.hasScanDur) {
      defaultConfig.scanDur = 3;
      defaultConfig.haloDur = 2;
    }

    componentRegistry.register({
      type: `datav-decoration-${meta.idx}`,
      name: meta.name,
      icon: meta.icon,
      description: meta.desc,
      category: "datav",
      version: "1.0.0",
      builtIn: true,
      enabled: true,
      defaultSize: meta.defaultSize,
      minSize: meta.minSize,
      defaultConfig,
      capabilities: { resizable: true, rotatable: false, draggable: true, connectable: false, embeddable: false },
      renderer: lazy(() => import("./renderers/DataVRenderer").then(m => ({ default: m.DataVRenderer }))),
      configSchema: schema,
    });
  }

  const decorationTypes = componentRegistry.getByCategory("decoration");
  const titleTypes = componentRegistry.getByCategory("decoration-title");
  const datavTypes = componentRegistry.getByCategory("datav");
  const allDecorationTypes = [...decorationTypes, ...titleTypes, ...datavTypes];
  for (const def of allDecorationTypes) {
    def.defaultConfig = { ...def.defaultConfig, ...ANIMATION_DEFAULTS };
    const existingKeys = new Set((def.configSchema || []).map((s: any) => s.key));
    const newSchemaEntries = ANIMATION_SCHEMA.filter((s) => !existingKeys.has(s.key));
    def.configSchema = [...(def.configSchema || []), ...newSchemaEntries];
  }
}
